language: node_js
node_js:
  - '7'
services:
  - mongodb
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
env:
  - CXX=g++-4.8 APP_SECRET='jaksnfwiutwhetlkwnrwonr923huijo23jrw' MONGODB_URI='mongodb://localhost/travis' AWS_BUCKET='' AWS_ACCESS_KEY_ID='' AWS_SECRET_ACCESS_KEY='' PORT=3000 API_URL='http://localhost:3000'
sudo: required
before_script: npm i
script:
  - npm test
  - npm run lint


PORT=3000
MONGODB_URI='mongodb://localhost/dev'
API_URL='http://localhost:3000'
APP_SECRET='lsdkfjkaldsfew9043ukdfakld9fa90d9f0ds90f'

AWS_BUCKET='upload-avatar'
AWS_ACCESS_KEY_ID=''
AWS_SECRET_ACCESS_KEY=''
